# Generated by Django 4.2.9 on 2026-10-03 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=30, unique=True, verbose_name='案件编号')),
                ('reason', models.CharField(choices=[('package_damaged', '包装破损'), ('quality_suspect', '质量存疑'), ('expired', '已过期'), ('other', '其他')], max_length=20, verbose_name='发现原因')),
                ('reason_detail', models.TextField(blank=True, verbose_name='原因说明')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='影响数量')),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='剩余隔离数量')),
                ('quarantine_location', models.CharField(default='隔离区', max_length=100, verbose_name='隔离位置')),
                ('status', models.CharField(choices=[('open', '隔离中'), ('closed', '已结案')], default='open', max_length=20, verbose_name='状态')),
                ('found_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('found_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_quarantine_cases', to=settings.AUTH_USER_MODEL, verbose_name='发现人')),
            ],
            options={
                'verbose_name': '隔离处置案件',
                'verbose_name_plural': '隔离处置案件',
                'db_table': 'wh_quarantine_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('release', '放行'), ('concession', '让步接收'), ('return', '退回'), ('destroy', '销毁')], max_length=20, verbose_name='处置方式')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='处置数量')),
                ('reason', models.TextField(blank=True, verbose_name='处置理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已执行'), ('rejected', '已拒绝'), ('revoked', '已撤销')], default='pending', max_length=20, verbose_name='状态')),
                ('approval_opinion', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quarantine_decisions', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='warehouse.quarantinecase', verbose_name='隔离案件')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_quarantine_decisions', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_quarantine_decisions', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
            ],
            options={
                'verbose_name': '隔离处置决定',
                'verbose_name_plural': '隔离处置决定',
                'db_table': 'wh_quarantine_decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='quarantined_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='隔离数量'),
        ),
        migrations.CreateModel(
            name='QuarantineMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('quarantine', '隔离入库'), ('release', '放行回库'), ('concession', '让步接收回库'), ('return', '退回出库'), ('destroy', '销毁出库'), ('revoke_release', '撤销放行'), ('revoke_concession', '撤销让步接收'), ('revoke_return', '撤销退回'), ('revoke_destroy', '撤销销毁')], max_length=20, verbose_name='移动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='移动数量')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='移出位置')),
                ('to_location', models.CharField(blank=True, max_length=100, verbose_name='移入位置')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.quarantinecase', verbose_name='隔离案件')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.quarantinedecision', verbose_name='关联决定')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='warehouse.quarantinemovement', verbose_name='被冲销的流水')),
            ],
            options={
                'verbose_name': '隔离库存移动流水',
                'verbose_name_plural': '隔离库存移动流水',
                'db_table': 'wh_quarantine_movement',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '复检合格'), ('fail', '复检不合格'), ('partial', '部分合格')], max_length=20, verbose_name='复检结果')),
                ('conclusion', models.TextField(verbose_name='复检结论')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='复检时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='warehouse.quarantinecase', verbose_name='隔离案件')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_inspections', to=settings.AUTH_USER_MODEL, verbose_name='复检人')),
            ],
            options={
                'verbose_name': '隔离复检记录',
                'verbose_name_plural': '隔离复检记录',
                'db_table': 'wh_quarantine_inspection',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.AddField(
            model_name='quarantinecase',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_cases', to='warehouse.goods', verbose_name='货物'),
        ),
        migrations.AddField(
            model_name='quarantinecase',
            name='stock_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_cases', to='warehouse.stockin', verbose_name='来源入库记录'),
        ),
    ]
