# Generated by Django 4.2.9 on 2026-10-03 01:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('release', '准予放行'), ('concession', '让步接收'), ('return', '退回供应商')], max_length=20, verbose_name='审批决定')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='决定处置数量')),
                ('target_location', models.CharField(blank=True, max_length=100, verbose_name='放行/让步入库位置')),
                ('opinion', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '隔离处置审批',
                'verbose_name_plural': '隔离处置审批',
                'db_table': 'wh_quarantine_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='案件编号')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('discovery_reason', models.CharField(choices=[('package_damaged', '包装破损'), ('label_missing', '标识缺失'), ('quality_abnormal', '质量异常'), ('quantity_shortage', '数量短少'), ('other', '其他')], max_length=30, verbose_name='发现原因')),
                ('reason_detail', models.TextField(blank=True, verbose_name='原因说明')),
                ('affected_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='影响数量')),
                ('quarantine_location', models.CharField(default='隔离区', max_length=100, verbose_name='隔离位置')),
                ('origin_location', models.CharField(blank=True, max_length=100, verbose_name='原存放位置')),
                ('status', models.CharField(choices=[('pending', '待复检'), ('reinspected', '已复检待审批'), ('released', '部分放行'), ('concession', '让步接收'), ('returned', '退回'), ('revoked', '已撤销')], default='pending', max_length=20, verbose_name='案件状态')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结案时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('discoverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_quarantine_cases', to=settings.AUTH_USER_MODEL, verbose_name='发现人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_cases', to='warehouse.goods', verbose_name='货物')),
                ('stock_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_cases', to='warehouse.stockin', verbose_name='入库记录')),
            ],
            options={
                'verbose_name': '隔离处置案件',
                'verbose_name_plural': '隔离处置案件',
                'db_table': 'wh_quarantine_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('quarantine_in', '移入隔离区'), ('quarantine_out', '移出隔离区（放行/让步）'), ('return_out', '退回出库'), ('transfer', '库位转移'), ('reversal', '撤销反向移动')], max_length=20, verbose_name='移动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='移动数量')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='来源位置')),
                ('to_location', models.CharField(blank=True, max_length=100, verbose_name='目标位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='是否已被撤销')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.quarantineapproval', verbose_name='来源审批')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.quarantinecase', verbose_name='所属案件')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='warehouse.stockmovement', verbose_name='被撤销的原移动')),
            ],
            options={
                'verbose_name': '库存移动',
                'verbose_name_plural': '库存移动',
                'db_table': 'wh_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='单元序号')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='单元数量')),
                ('status', models.CharField(choices=[('held', '隔离中'), ('partial', '部分处置中（剩余隔离）'), ('released', '已放行'), ('concession', '让步接收'), ('returned', '已退回')], default='held', max_length=20, verbose_name='处置状态')),
                ('hold_active', models.BooleanField(db_index=True, default=True, verbose_name='隔离是否有效')),
                ('hold_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='有效隔离数量')),
                ('released_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='累计放行数量')),
                ('concession_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='累计让步接收数量')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='累计退回数量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='warehouse.quarantinecase', verbose_name='所属案件')),
            ],
            options={
                'verbose_name': '隔离处置单元',
                'verbose_name_plural': '隔离处置单元',
                'db_table': 'wh_quarantine_unit',
                'ordering': ['case_id', 'seq'],
                'unique_together': {('case', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='QuarantineRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='撤销时间')),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revocation', to='warehouse.quarantineapproval', verbose_name='被撤销的审批')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_revocations', to=settings.AUTH_USER_MODEL, verbose_name='撤销操作人')),
            ],
            options={
                'verbose_name': '处置撤销记录',
                'verbose_name_plural': '处置撤销记录',
                'db_table': 'wh_quarantine_revocation',
            },
        ),
        migrations.CreateModel(
            name='QuarantineReinspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', '待复检'), ('qualified', '复检合格（可放行）'), ('concession', '让步可用'), ('unqualified', '复检不合格（建议退回）')], max_length=20, verbose_name='复检结果')),
                ('qualified_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='复检合格数量')),
                ('concession_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='让步数量')),
                ('unqualified_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='不合格数量')),
                ('finding', models.TextField(blank=True, verbose_name='复检情况')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='复检时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinspections', to='warehouse.quarantinecase', verbose_name='所属案件')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_reinspections', to=settings.AUTH_USER_MODEL, verbose_name='复检人')),
            ],
            options={
                'verbose_name': '复检记录',
                'verbose_name_plural': '复检记录',
                'db_table': 'wh_quarantine_reinspection',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('release', '放行'), ('concession', '让步接收'), ('return', '退回')], max_length=20, verbose_name='处置类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='处置数量')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='warehouse.quarantineapproval', verbose_name='审批决定')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='warehouse.stockmovement', verbose_name='库存移动')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='warehouse.quarantineunit', verbose_name='处置单元')),
            ],
            options={
                'verbose_name': '处置落账',
                'verbose_name_plural': '处置落账',
                'db_table': 'wh_quarantine_disposition',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='quarantineapproval',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='warehouse.quarantinecase', verbose_name='所属案件'),
        ),
        migrations.AddField(
            model_name='quarantineapproval',
            name='reinspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='warehouse.quarantinereinspection', verbose_name='依据复检记录'),
        ),
    ]
