# Generated by Django 4.2.9 on 2026-10-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_quarantinecase_quarantinedecision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarantinemovement',
            options={'ordering': ['id'], 'verbose_name': '隔离库存移动流水', 'verbose_name_plural': '隔离库存移动流水'},
        ),
    ]
